//! Examples of using `safe_index`.
//!
//! Do not use the types in this module.

/// Example of zero-cost wrapping. **Do not use this.**
///
/// This module is generated by
///
/// ```
/// use safe_index::new_index;
/// new_index!{
///     /// Index of a variable.
///     VarIndex
///     /// Range over `VarIndex`.
///     range: VarRange
///     /// Set of variable indices.
///     btree set: VarBSet
///     /// Map of variable indices.
///     btree map: VarBMap
///     /// Vector indexed by variable indices.
///     map: VarMap with iter: VarMapIter
/// }
/// fn main() {
///     use std::mem::size_of;
///     assert_eq!( size_of::<VarIndex>(), size_of::<usize>() );
///     assert_eq!( size_of::<VarRange>(), 2 * size_of::<usize>() );
///     assert_eq!( size_of::<VarMap<String>>(), size_of::<Vec<String>>() );
/// }
/// ```
pub mod basic {
    new_index! {
        /// Index of a variable.
        VarIndex
        /// Range over `VarIndex`.
        range: VarRange
        /// Set of variable indices.
        btree set: VarBSet
        /// Map of variable indices.
        btree map: VarBMap
        /// Vector indexed by variable indices.
        map: VarMap with iter: VarMapIter
    }
}
